name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 0 * * *"   # har raat 12 baje run hoga
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Step 1: Contribution data generate (needs token)
      - name: Generate profile data
        uses: yoshi389111/github-profile-3d-contrib@0.10.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: 3D SVG render
      - name: Generate 3D SVG
        run: |
          npm install -g github-profile-3d-contrib
          github-profile-3d-contrib --no-fetch

      # Step 3: Commit & push
      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: generate 3D contribution calendar"
          git push
