name: GitHub Metrics

on:
  schedule: # roz subah chalega
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: akshayverma3685
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
